modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="terrainfinita"
version="1.0.0"
displayName="Terra Infinita"
description='''Terra que faz plantacoes crescerem na hora e gerarem drops infinitos num hopper/bau. Funciona com Mystical Agriculture.'''

[[dependencies.terrainfinita]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.terrainfinita]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
